#!/usr/bin/env python
# coding: utf-8


import sqlalchemy
import pyodbc
from sqlalchemy import create_engine
import urllib

#returns engine object
def make_connection( database ):
    
    servername = 'server_name
    dbname = database
    
    engine = sqlalchemy.create_engine(
    'mssql+pyodbc://@' + servername + '/' + dbname + '?trusted_connection=yes&driver=ODBC+Driver+13+for+SQL+Server'
    )
    return engine   

#generate query to get all columns
def _select_all_columns(table):
    return "SELECT * FROM"+" "+table


#generate query with list of columns
def _select_specific_columns(table , columns):

    columns_query = ""
    for i in range(len(columns)):
        columns_query+=columns[i]+","
    columns_query = columns_query[ 0 : len(columns_query) - 1] + " "     
    base_query = "SELECT"+" "+columns_query+""+"FROM"+" "+table
      
    return base_query

#get data
def get_data(query,engine):
    data = pd.read_sql_query(query,engine)
    return data
